# Generated by Django 5.1.1 on 2024-09-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="clinics",
            field=models.ManyToManyField(
                through="core.DoctorClinicAffiliation", to="core.clinic"
            ),
        ),
    ]
