# Generated by Django 5.1.1 on 2024-09-25 01:09

from django.db import migrations


def create_predefined_procedures(apps, schema_editor):
    Procedure = apps.get_model("core", "Procedure")  # Replace 'core' with your app name

    # Predefined list of procedures
    predefined_procedures = [
        "Cleaning",
        "Filling",
        "Root Canal",
        "Crown",
        "Teeth Whitening",
    ]

    # Create procedures if they don't already exist
    for procedure_name in predefined_procedures:
        Procedure.objects.get_or_create(name=procedure_name)


class Migration(migrations.Migration):

    dependencies = [
        # Add the most recent migration this depends on
        ("core", "0004_clinic_city_clinic_country_clinic_state"),
    ]

    operations = [
        migrations.RunPython(create_predefined_procedures),
    ]
