# Generated by Django 5.1.1 on 2024-09-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_doctor_patients_doctor_phone_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='doctorclinicaffiliation',
            constraint=models.UniqueConstraint(fields=('doctor', 'clinic'), name='unique_affiliation'),
        ),
    ]
