# Generated by Django 5.1.1 on 2024-09-25 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_doctorclinicaffiliation_unique_affiliation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='procedures',
            new_name='procedures_done',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='date',
            new_name='visit_date',
        ),
    ]
