# Generated by Django 5.1.1 on 2024-09-29 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_procedures_visit_procedures_done_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
    ]
