from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from .views import (
    UserProfileView,
    EditUserProfileView,
    HomePageView,
    ClinicListView,
    ClinicCreateView,
    ClinicDetailView,
    ClinicUpdateView,
    PatientListView,
    PatientDetailView,
    PatientUpdateView,
    DoctorListView,
    DoctorDetailView,
    DoctorUpdateView,
    DoctorCreateView,
    PatientCreateView,
    load_states,
    load_cities,
    edit_affiliation,
    create_affiliation,
    delete_affiliation,
    add_visit,
    schedule_appointment,
    ajax_load_doctors,
    ajax_load_procedures,
    ajax_load_timeslots,
    ajax_load_clinics,
)

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("login/", LoginView.as_view(template_name="core/login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="login"), name="logout"),
    path("accounts/profile/", UserProfileView.as_view(), name="profile"),
    path("accounts/profile/edit/", EditUserProfileView.as_view(), name="profile-edit"),
    path("clinics/", ClinicListView.as_view(), name="clinic-list"),
    path("clinics/<int:pk>/", ClinicDetailView.as_view(), name="clinic-detail"),
    path("clinics/<int:pk>/edit/", ClinicUpdateView.as_view(), name="clinic-update"),
    path("clinics/new/", ClinicCreateView.as_view(), name="clinic-create"),
    path(
        "clinic/<int:clinic_id>/create-affiliation/",
        create_affiliation,
        name="create-affiliation",
    ),
    path(
        "affiliation/<int:affiliation_id>/edit/",
        edit_affiliation,
        name="edit-affiliation",
    ),
    path(
        "affiliation/<int:affiliation_id>/delete/",
        delete_affiliation,
        name="delete-affiliation",
    ),
    path("patients/", PatientListView.as_view(), name="patient-list"),
    path("patients/<int:pk>/", PatientDetailView.as_view(), name="patient-detail"),
    path("patients/<int:pk>/edit/", PatientUpdateView.as_view(), name="patient-update"),
    path("patients/<int:patient_id>/add-visit/", add_visit, name="add-visit"),
    path(
        "patients/<int:patient_id>/add-appointment/",
        schedule_appointment,
        name="schedule-appointment",
    ),
    path("patients/new/", PatientCreateView.as_view(), name="patient-create"),
    path("doctors/", DoctorListView.as_view(), name="doctor-list"),
    path("doctors/<int:pk>/", DoctorDetailView.as_view(), name="doctor-detail"),
    path("doctors/<int:pk>/edit/", DoctorUpdateView.as_view(), name="doctor-update"),
    path("doctors/new/", DoctorCreateView.as_view(), name="doctor-create"),
    path("ajax/load-states/", load_states, name="ajax_load_states"),
    path("ajax/load-cities/", load_cities, name="ajax_load_cities"),
    path("ajax/load-clinics/", ajax_load_clinics, name="ajax_load_clinics"),
    path("ajax/load-doctors/", ajax_load_doctors, name="ajax_load_doctors"),
    path("ajax/load-procedures/", ajax_load_procedures, name="ajax_load_procedures"),
    path("ajax/load-timeslots/", ajax_load_timeslots, name="ajax_load_timeslots"),
    path("api/", include("api.urls")),
]
